version: "3.8"
services:

  dynamodb-local-production:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local-production
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  dynamodb-admin-production:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8010:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local-production:8000"
      AWS_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local-production
    restart: unless-stopped

  dynamodb-local-it:
#    command: "-jar DynamoDBLocal.jar"
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local-it
    ports:
      - "8008:8000"

  dynamodb-admin-it:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8011:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local-it:8000"
      AWS_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local-it
    restart: unless-stopped

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.15
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  mqtt-it:
    container_name: mqtt-it
    image: eclipse-mosquitto:2.0.15
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1882:1883

volumes:
  data: {}

networks:
  default: