version: "3.8"
services:

  mongodb-production:
    image: mongo
    container_name: dm-mongodb-production
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express-production:
    image: mongo-express
    container_name: dm-mongo-express-production
    ports:
      - 8087:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb-production
    restart: unless-stopped

  mongodb-it:
    image: mongo
    container_name: dm-mongodb-it
    ports:
      - 27016:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express-it:
    image: mongo-express
    container_name: dm-mongo-express-it
    ports:
      - 8086:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb-it
    restart: unless-stopped

#  postgres:
#    image: postgres:13-alpine
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=training
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - PGDATA=/database
#    command: [ "postgres", "-c", "log_statement=all" ]
#    #    volumes:
#    #      - ./my-db:/database
#  pgadmin:
#    image: dpage/pgadmin4
#    ports:
#      - 8000:80
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@training.pl
#      - PGADMIN_DEFAULT_PASSWORD=admin

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0.15
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  data: {}

networks:
  default: