### Encode to Base64 format: jan@example.com:MyPassword
### Result: amFuQGV4YW1wbGUuY29tOk15UGFzc3dvcmQ=

### get information about me
GET http://localhost:8080/api/v1/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic c3RlZmFuQGV4YW1wbGUuY29tOnBhc3N3b3Jk

### get information about me
GET http://localhost:8080/api/v1/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuQGV4YW1wbGUuY29tOk15UGFzc3dvcmQ=


### get all measurementr from device with id
GET http://localhost:8080/api/v1/devices/3/measurements
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuQGV4YW1wbGUuY29tOk15UGFzc3dvcmQ=
