### get device
GET http://localhost:8081/api/v1/device
Accept: application/json
Content-Type: application/json

### get device settings
GET http://localhost:8081/api/v1/device/settings
Accept: application/json
Content-Type: application/json

### update device
PUT http://localhost:8081/api/v1/device
Accept: application/json
Content-Type: application/json

{
  "id": "deviceId123",
  "ownerId": "ownerId",
  "name": "deviceName"
}