mqtt:
  username: admin
  password: qwerty
  server:
    uri: tcp://localhost:1883
spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: projectTwo
      port: 27017
      host: localhost
      auto-index-creation: true