mqtt:
  username: admin
  password: qwerty
  server:
    uri: tcp://mqtt:1883
spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

aws:
  dynamoDBUrl: ${DYNAMO_ENDPOINT}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
