mqtt:
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  server:
    uri: ${MQTT_ENDPOINT}
spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

aws:
  dynamoDBUrl: ${DYNAMO_ENDPOINT}
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
