mqtt:
  username: admin
  password: qwerty
  server:
    uri: tcp://localhost:1882
server:
  port: 0
spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1

aws:
  dynamoDBUrl: http://localhost:8008
  accessKey: local
  secretKey: local
  region: eu-north-1
local:
  folder: testRepo/