name: CI - Build Main Backend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - backend/device-management-main/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      dynamodb-local-it:
        image: amazon/dynamodb-local:latest
        ports:
          - "8008:8000"
      mqtt-it:
        image: rafalnowak444/dm-mosquitto:latest
        ports:
          - 1882:1883
        env:
          MQTT_USERNAME: "admin"
          MQTT_PASSWORD: "qwerty"
          MQTT_LISTENER: "1883"

    defaults:
      run:
        working-directory: ./backend/device-management-main
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify
