name: Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Discord pull request message
        run: >
          curl -X POST -H 'Content-type: application/json'
          curl -H "Content-Type: application/json" -d '{"username": "group-project-device-management", "content": "pull request ${{ github.event.pull_request.title }} has been created"}'
          ${{ secrets.Discord_WEBHOOK_URL }}
     
